[package]
name = "hangar"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
criterion = "0.5.1"
polars = { version = "0.41.3", features = ["lazy", "csv", "dtype-struct"] }

[[bench]]
name = "data"
harness = false
